version: "3.3"

services:
  database:
    container_name: node-back-database
    image: postgres
    network_mode: host
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  # api:
  #   container_name: node-back-api
  #   build: .
  #   network_mode: host
  #   depends_on:
  #     - database
